### ISSUE TITLE
RuntimeException: Failed to start transaction

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#132]
Hi, after upgrading to v1.6.2, I started notice strange error in the logs, after each restart I see:
```bash
...
21:32:23.580 [Main] INFO  LINSTOR/Controller - SYSTEM - Controller initialized
21:32:38.634 [MainWorkerPool-1] ERROR LINSTOR/Controller - SYSTEM - Failed to start transaction [Report number 5EA74F4D-00000-000000]
```

[5EA74F4D-00000-000000.log](https://github.com/LINBIT/linstor-server/files/4542174/5EA74F4D-00000-000000.log)
.
```bash
...
21:36:56.633 [Main] INFO  LINSTOR/Controller - SYSTEM - Controller initialized
21:37:01.254 [MainWorkerPool-1] ERROR LINSTOR/Controller - SYSTEM - com.linbit.linstor.transaction.TransactionException: Failed to start transaction [Report number 5EA7505D-00000-000000]
```

[5EA7505D-00000-000000.log](https://github.com/LINBIT/linstor-server/files/4542177/5EA7505D-00000-000000.log)

**Comment by ghernadi** [comment]
Thats strange. From the stacktrace this seems like psql-jdbc internal bug, as all Linstor is doing is calling a `getConnection` method.. 
The funny part is that we upgraded the jdbc driver for psql from Linstor version 1.5.2 -> 1.6.0, but didnt touch any jdbc drivers since 1.6.0. 

Not sure what we can do here, especially since this kind of error did not occur in our automated tests.. Currently Linstor is using 42.2.12 of the psql jdbc drier. You could try to manually replace the jdbc driver with other [versions](https://jdbc.postgresql.org/download.html) and see if the problem persists.

**Comment by kvaps** [comment]
Heh It seems problem somewhere in my environment, it was solved by itself when I started debuging it :-)

I'll reopen this issue if it will repeated again
