### ISSUE TITLE
Can not specify autoplace strategy

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#140]
```bash
# linstor controller set-property Autoplacer/Weights/MinReservedSpace 1
ERROR:
Description:
    The value '1' is not valid.
Details:
    The value must match: ^[0-9]+([.][0-9]+)?}
command terminated with exit code 10
```

```bash
# linstor controller set-property Autoplacer/Weights/MinReservedSpace '1}'
SUCCESS:
    Successfully set property 'Autoplacer/Weights/MinReservedSpace' to value '1}'
```

And after this auto-placing is not working anymore :)

**Comment by ghernadi** [comment]
Sorry for this stupid typo - at least it was consistently copy pasted to all weight properties :joy: 

> And after this auto-placing is not working anymore :)

You should still be able to remove the property with   
`linstor controller set-property Autoplacer/Weights/MinReservedSpace`
At least then the autoplacer works again (although only with the MaxFreeSpace strategy)

Typo will be fixed in next release.
