### ISSUE TITLE
Deprecate plainConnector

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#147]
Hi do you have plans for deprecate plainConnector?

I guess that all possible clients and drivers for linstor already switched to use RestAPI instead of plainConnector, but linstor-server still listens on `3376` port and have plainConnector enabled by default:

It can't be simple disabled using option or environment variable, it can be done only via [debug-console](https://github.com/LINBIT/linstor-server/issues/5#issuecomment-434240233).

I'm not sure but is there any sense to disable it if I configured mutual SSL authentification for the clients, I guess it might become to be kind of security hole in the future.

Thank you!

**Comment by ghernadi** [comment]
Funny that you mention the debug-console, because apart from the debug-console you mentioned we also have debug-commands (old protobuf-style, no REST interface) which actually can use the PlainConnector. 

I guess it would make more sense to allow again the user to modify the controllers `netcom/*` namespace (as it was intended from the first second on) where you can then do something like `c sp netcom/PlainConnector/enabled false` (you maybe have to restart the controller, not entirely sure right now) and the PlainConnector should no longer start.

**Comment by kvaps** [comment]
It would be nice to provide some command line option or some environment variable to make it possible define this behavior outside the runtime

Or make it listen the localhost addresses only.

**Comment by rp-** [comment]
plain connector isn't enabled anymore on default
