### ISSUE TITLE
Allow specify nested zfs datasets

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#2]
# Feature Request
## Description

Please allow to specify nested zfs datasets:

```
linstor storage-pool create node1 zfspool zfs rpool/linstor
```

It is very usful for having many pools on same devices.
Also you can specify different options for different zfs datasets.
Any way always use root pool for placing volumes usualy is not good practice.

## Use case

For example I have one root zfs pool `rpool`, and I want to store docker images and drbd drives there, plus some data, and have them separated from each other. I can create few datasets for this purpose:
```
rpool/data (some filesystem)
rpool/docker (docker zvols)
rpool/linstor (linstor zvols)
```
Then I need to configure linstor for use `rpool/linstor` (not `rpool`)

### Actual Behavior

Currently this command returns:

```
ERROR:
Description:
    Invalid property value
Cause:
    The value 'rpool/linstor' is not valid for the key 'StorDriver/ZPool'
Details:
    The value must match '[a-zA-Z0-9_-]+'
    Node: node1, Storage pool name: zfspool
```

**Comment by raltnoeder** [comment]
Enabling the use of nested datasets would be trivial, we are currently trying to figure out whether we can enable this feature and still have sane space reporting, because ZFS reports the statistics for the entire pool for each nested dataset. LINSTOR has support for shared spaces that span multiple storage pools, but the ZFS space management is more complex than that, since it also allows the reservation of some space for nested datasets, but then adds in the space of the parent pool in space reporting.
Anyhow, this will most probably be available in a future release, with more or less sane effects on the space reported for such configurations.

**Comment by rp-** [comment]
This should also work now.
