### ISSUE TITLE
Problem building drbd-9.0.21-1 on CentOS  7.7.1908 (Kernel )

### ISSUE THREAD

**Issue by Ilyashestopalov** [LINBIT/linstor-server#228]
Hello!
I have a problem building a kernel module from tarball drbd-9.0.21-1.tag.gz. Can you help me ?

Operation system: CentOS Linux release 7.7.1908 (Core)
Kernel: 5.4.114-1.el7.elrepo.x86_64 (https://elrepo.org/linux/kernel/el7/x86_64/RPMS/kernel-lt-5.4.114-1.el7.elrepo.x86_64.rpm)
glibc: glibc-2.17-292.el7.x86_64

make-trace [file](url)  as an attachment
[make-trace.txt](https://github.com/LINBIT/linstor-server/files/6400783/make-trace.txt)

**Comment by rck** [comment]
I'm really not sure why you think building a kernel module has anything to do with a java based user space program (LINSTOR), but anyways:

- 9.0.21 is so out of date (November 2019) that you need to update anyways
- as you might know, we need compat code in the kernel module so that we can compile it for various kernels/distributions. This release obviously did not contain compat code for your kernel. We don't backport compat patches to outdated, years old releases.
- we try hard that the code compiles for standard RHEL and Centos (as in the "old days"). We don't care for any elrpo kenels. It might work, it might not.

So, use a version of drbd that is not outdated for years, you might be lucky. If not you might have more luck with a kernel that is close to one RHEL ships.

**Comment by Ilyashestopalov** [comment]
I created a ticket here because there is no "issues" section in the repository https://github.com/LINBIT/drbd
I am grateful for the answer!

**Comment by rck** [comment]
Thanks for the reminder, I turned issues on for drbd. Usually we prefer that kind of questions to be asked on the drbd-user mailing list.
