### ISSUE TITLE
No way to restore a volume definition from a snapshot with a storage-pool

### ISSUE THREAD

**Issue by alexisries** [LINBIT/linstor-server#24]
When we create a volume definition with 'linstor vd create', we have the '--storage-pool' option, this creates the StorPoolName property. The property 'StorPoolName' is not restored using this command 'linstor s vd restore'.

**Comment by JoelColledge** [comment]
Snapshots are created and restored using the using the underlying storage technology, e.g. LVM. So the snapshot only exists within the storage pool where the resource was and can only be restored there. That's why 'linstor s vd restore' does not allow the storage pool to be set.

Linstor does not currently have the ability to copy snapshots between storage pools. It might be an interesting feature to add.

What is your use case?

**Comment by alexisries** [comment]
No, it was not my problem, I was wrong in my explanation, so I changed my comment.
Instead, the property containing the storage pool is not restored to the volume definition.

**Comment by JoelColledge** [comment]
OK, now I understand better. At the moment, the storage pool for the restored snapshot volumes is set directly at the volume level, but the original configuration is lost. We should also store any 'StorPoolName' property set on the volume definition when taking a snapshot and restore it again when restoring the volume definitions, so that additional resources created in the new resource definition use the expected storage pool.

For completeness, we should also store any 'StorPoolName' property set on the resource when taking a snapshot and restore it again when restoring the resources. However, this is only relevant when an additional volume definition is subsequently added, which is not a very common use case.

We'll look into adding this. PRs always welcome!

**Comment by ghernadi** [comment]
Snapshots were reworked with `v1.4.0` where all properties should now be copied when a snapshot is created. 

Feel free to reopen this issue if the necessary.
