### ISSUE TITLE
How does Autoplacer/MinReservedSpace strategy work?

### ISSUE THREAD

**Issue by chiraganand-e2e** [LINBIT/linstor-server#254]
For example, if I have 2 DRBD (linstor satellite) storage nodes (`node1`, `node2`) with place-count as 2 which are already in use and I add 2 more nodes (`node3` and `node4`) of different capacity to the same storage pool then how does _MinReservedSpace_ strategy make a decision? Given that two previous two nodes have different reserved capacity than the new ones, to whom will this strategy give preference to?

Say, node1 and node2 have _30TB_ of reserved capacity and node3 and node4 have _20TB_ reserved capacity, then does it mean node1 and node2 will be given preference by this strategy?

**Comment by ghernadi** [comment]
Thank you for making re-read the code, which actually had a bug.

Some details:
In Linstor we usually have 3 sizes: first, the size the user entered. For demonstration purposes I go with something extremely small as 10M. Additionally Linstor distinguishes between _usable_ and _allocated_ size. 
When Linstor gets the job to create a device that is "at least" 10M, due to for example LVM's default extent size of 4M this 10M will be rounded up to 12M. That is the _usable_ size. 
With Linstor's `LVM` provider those 12M are also the _allocated_ size. However, with `LVM_THIN` things are different as the _allocated_ size is initially almost 0 (thin provisioning) and keeps growing by time without exceeding _usable_ size. 

With that, the strategy MinReservedSpace works by trying give the storage pool with the lowest sum of usable space a higher score. 

The mentioned bug was that the actual code by mistake summed up the _allocated_ size (which will grow during usage) instead of the _usable_ size (the "limit" of the specific thin volume).

> Say, node1 and node2 have 30TB of reserved capacity and node3 and node4 have 20TB reserved capacity, then does it mean node1 and node2 will be given preference by this strategy?

No, its the opposite. The thinking behind this is that if you have for example 50TB capacity on all 4 nodes, node1 and 2 already have thin volumes which already consumes 10TB but could grow during usage to up to 30TB, whereas node3 and 4 have thin volumes consuming 15TB but can only grow up to 20TB, node3 and 4 still have more unreserved capacity than node1 and 2. 

That means, MinReservedSpace tries to prioritize storage pools with less reserved space (depending on Linstor's _usable_ size, i.e. the "limit" of each thin volume), whereas MaxFreeSpace tries to prioritize storage pool with more unallocated space (which might shrink over time even without new resoures as existing thin volumes might grow)


Hope this explanation helps rather than adding more confusion :) 

However, I will also revisit the documentation as that could also be more clear about these strategies.
