### ISSUE TITLE
Cannot migrate resource from LVM to ZFS, disk size mismatch

### ISSUE THREAD

**Issue by elonen** [LINBIT/linstor-server#36]
While trying to migrate a 32GB resource from (thick) LVM to (thick) ZFS storage pool, I got the following error in dmesg, after which connection to the ZFS-backed DRBD node was immediately disconnected:

`drbd vm-121-www-data-2/0 drbd1011 mox-a: The peer's disk size is too small! (67108864 < 67110832 sectors)`

My idea was to recreate & resync the resource on ZFS one node at a time, until not no more LVM backed resource remain. The command was `linstor r create -s pool_ssd mox-a vm-121-www-data-2`, which got stuck for a long time and then finally printed: `Error: Socket timeout, no data received since 300192ms.`.

**Comment by JoelColledge** [comment]
Yes, this is a known issue that occurs due to rounding differences in the storage backends when mixing different storage pool types (or potentially differently configured storage pools of the same type). A workaround is just to increase the volume size slightly with `volume-definition set-size` after adding the ZFS node.

**Comment by raltnoeder** [comment]
This will probably be fixed or at least worked around one way or the other in some future version, we have been discussing various options to avoid this problem.
A possible fix would be the use of the `size` parameter in DRBD configuration files, but that complicates the automatic resize feature significantly. A possible workaround would be to introduce a configurable alignment in LINSTOR, so that all resources are created with the same size on various storage backends.
