### ISSUE TITLE
Satellite and Server binding ipv6 only

### ISSUE THREAD

**Issue by andreas-p** [LINBIT/linstor-server#38]
Both linstor-server/satellite 0.7.3 bind to ipv6 only. They should bind to both ipv4 and ipv6. Tested on debian-stretch.
Interestingly, if the --bind-address is set to a v4 address, the protocol used is still v6 when examining the binding with netstat.

**Comment by ghernadi** [comment]
I am not sure about if Linstor really should bind to both by default.

However, I have created an internal ticket for adding new APIs for creation, modification and deletion of TcpServices, so that you can manage them by your own. For now such management is only possible by manually modifying some entries in our properties-database-table.

Regarding the `--bind-address` (as well as the `--plain-port` by the way): yes, that is a bug, as those two parameters were completely ignored by the controller.  
The satellite also has those arguments, but the satellite really uses them as expected :)

**Comment by raltnoeder** [comment]
The default bind address is `::0`, which normally enables IPv6 and IPv4 addresses and listens on all interfaces. E.g., all our test system connectors listen on `::0`, and clients can connect using both, IPv4 and IPv6.

I am not sure what happens if an interface has only an IPv4 address, but no IPv6 address -- whether the server will listen on such an interface or not has not been tested yet.
Anyhow, the bind address is configurable, and for the `::0` and `::1` addresses, there is also an automatic failback for the case that the entire IPv6 address family is not supported by the platform.

We can not bind the same socket to more than one address at a time, so binding the same connector to both, an explicit IPv6 and an explicit IPv4 address, is not possible. It is however possible to configure multiple connectors, some with IPv4 and some others with IPv6 bind addresses.

**Comment by andreas-p** [comment]
This is what I see with netstat -antp:

tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      897/sshd            
tcp6       0      0 :::22                   :::*                    LISTEN      897/sshd            
tcp6       0      0 :::3376                 :::*                    LISTEN      10043/java          
tcp6       0      0 :::3366                 :::*                    LISTEN      874/java            

sshd is configured with "ListenAddress 0.0.0.0 \n ListenAddress ::" by default.

Actually, I can connect via telnet to satellite or controller using an interface ipv4 address when doing so on the same machine:
tcp        0      0 192.168.171.3:42008     192.168.171.3:3366      ESTABLISHED 10304/telnet        
tcp6       0      0 192.168.171.3:3366      192.168.171.3:42008     ESTABLISHED 874/java            
The Linux tcp stack seems to make some internal conversion from tcp to tcp6 here.
But this does not work between different machines.

**Comment by raltnoeder** [comment]
I have now tested binding an interface that does not have any IPv6 addresses configured, but I cannot reproduce the behavior. In my test, the IPv4-only interface is bound by the netcom connectors with a `::0` bind address, and is reachable using its IPv4 address locally as well as remotely.
Test system was running Ubuntu 16.04.5 LTS with a 4.10.0 kernel.

Configuring two connectors, one bound to `0.0.0.0` and the other one bound to ::0, causes one of the two connectors to fail. Obviously, it would be possible to configure them on different TCP ports.

The problem may also be caused by the dual stack mode configuration, you can check the `net.ipv6.bindv6only` sysctl to determine what the current mode on your system is.
(Anyhow, the setting had no effect on our test system).

**Comment by andreas-p** [comment]
net.ipv6.bindv6only = 0, my system is Debian9 with kernel 4.18 from backports.
The interfaces have automatically generated IPV6 addresses, as well as (to get linstor running) static ipv6 addresses.
"Binding ::0 to IPV4 only interface" sounds strange, since ::0 isn't a legal IPV$ address. Again, something implicit seems to happen on your system, beyond net.ipv6.bindv6only according to your message.
I guess sshd et al use two binds using different address families explicitely, i.e. 0.0.0.0/AF_INET and ::0/AF_INET6. Looking at netstat output, linstor-server/satellite probably uses AF_INET6 only.

**Comment by andreas-p** [comment]
Ok, just tried with 4.9 kernel:
tcp6       0      0 192.168.171.4:3366      192.168.171.3:35340     ESTABLISHED 1770/java 
While this looks funny to me, ipv4 address with tcp6 family, the connection succeeds. Obviously, this ipv4/6 mixup was changed between 4.9 and 4.18.

**Comment by raltnoeder** [comment]
The socket interface that we are using (`java.nio.channel.ServerSocketChannel`) is completely abstract, and can only be bound once to a single bind address represented by an object implementing the `java.net.SocketAddress` interface. In our case, this is always an IP address, and that can either be IPv4 or IPv6 (`java.net.Inet4Address` or `java.netInet6Address`).

Regarding `net.ipv6.bindv6only`, as far as I have tested it, this setting does not appear to do what the documentation says it is supposed to do. This may be a bug in the Linux kernel, or the documentation may be inaccurate (e.g., might forget to mention that changing it requires reconfiguring the network cards, or something like that). It had no effect on our test system.

The bind address of the satellite's default netcom service can be changed in the `satellite_netcom.cfg` configuration file, e.g.:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>LINSTOR initial connector configuration</comment>
<entry key="type">plain</entry>
<entry key="bind-address">0.0.0.0</entry>
<entry key="port">3366</entry>
</properties>
```

The satellite also has a `--bind-address` command line option that can be used to override the default configuration.

The bind address of the controller's preconfigured PlainConnector netcom service can be set, while the Controller is stopped, using the LinstorConfig utility. The command (from the LINSTOR installation directory) is:
`java -cp lib/"*" com.linbit.linstor.core.LinstorConfig set-plain-listen database.cfg 0.0.0.0`

**Comment by andreas-p** [comment]
Very strange, after rebooting again into 4.18, ipv4 connection do work now...

Digging a little into net.ipv6.bindv6only, I think Java now sets the option IPV6_V6ONLY, which wasn't the case for a long time and prevented net.ipv6.bindv6only=1 as default in most distributions. It appears as best practice to only accept V6 on IPV6 interfaces for security reasons, but many simpler services don't take that extra step.

**Comment by raltnoeder** [comment]
I would be surprised if it did, because setting sysctl values requires root privileges, and our test system is running the controller in an unprivileged context. Some other piece of software may of course have set the value for whatever reason.
Anyway, good to hear that it works now.

**Comment by andreas-p** [comment]
IPV6_V6ONLY is a socket option, while net.ipv6.bindv6only is just a system-wide default if IPV6_V6ONLY is not explicitely set when binding the socket.
