### ISSUE TITLE
recycler: rename/move volumes instead of deleteing them

### ISSUE THREAD

**Issue by ggzengel** [LINBIT/linstor-server#390]
On ZFS I use zrepl on Proxmox for backup and life sync to external encrypted storage. 
This uses additional snapshots/bookmarks and holds.
ZFS don't delete holds even with forcing.

**Comment by ghernadi** [comment]
I am not really sure if I fully understand what you are suggesting here..

Do you suggest that LINSTOR should by default no longer delete any resource/snapshot when using ZFS but just rename the no longer used volumes to avoid naming conflicts? Until the zpool eventually runs full? And what then?

Either I am missing something, or that does not really sound like a thought through idea...

I am not really familiar with `zrepl`, but if you run into problems like "`zrepl` creates snapshots for its backing up procedure and those snapshots (which LINSTOR is not aware of since they were created outside of LINSTOR) prevent LINSTOR from deleting volumes due to the parent-child dependency within ZFS", then I have to ask if you cannot configure `zrepl` to no longer create backups for volumes that you intend to delete via LINSTOR?

**Comment by ggzengel** [comment]
There multiple reasons to move/rename volumes:
1. To recover volumes, after deleting from a Trojan or somebody else
2. To make sure the volume is deleted even it uses holds

I suggest to move volumes (and append delete date to volume name) to a user defined path.
The root is responsible to delete the volumes.

All ZFS based replication tools uses snapshots. Most are using holds.

From zrepl:
```
guarantee_resumability is the default value and guarantees that a replication step is always resumable and that incremental replication will always be possible. The implementation uses replication cursors, last-received-hold and step holds.
```

**Comment by ghernadi** [comment]
Sorry, but this will not happen. 
We have users with hundreds of nodes and thousands of resources. No longer deleting actual volumes but giving the "list to delete" to the admin could easily end up in a fulltime-job processing that list. 

Have you considered LINSTOR's `backup ship` feature for creating (incremental) backups? https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-linstor-snapshots-shipping-to-a-linstor-remote

Otherwise, if you still need this feature, feel free to fork LINSTOR and adjust as you see fit.

**Comment by ggzengel** [comment]
If I write the root is responsible I mean he has to install a cron job or something else.
An other solution is to use hook-script for rollback and deleting.
I know there is an open issue that linstor should use -r for deleting and role back.
