### ISSUE TITLE
Break Mariadb 10.3 in LinStor 1.*

### ISSUE THREAD

**Issue by proceau-envoyer** [LINBIT/linstor-server#72]
Hi,

when reinstall last version ( 1.0.1), the linstor controller say: Unsupported Database: MariaDB 10.3
all it's set, version, mariadb jar, lowercase, ...

**Comment by raltnoeder** [comment]
This is almost certainly due to a known bug in the version of Flyway (the database migrations library) used by LINSTOR.

The bug is described here:
https://github.com/flyway/flyway/issues/2339

The Flyway bug report contains these instructions for a possible workaround until we can deliver a version of LINSTOR with an updated Flyway library:

> Latest versions of MariaDB Connector/J driver return "MariaDB" server type instead of "MySQL", that's why Flyway worked with previous versions of this driver (Spring Framework and many projects had the same issue).
> 
> To make it work with 2.4.x: simply add useMysqlMetadata=true to your jdbc url -> driver will return "MySQL" server type.
