### ISSUE TITLE
"Wong" status on Linstor for Resource

### ISSUE THREAD

**Issue by proceau** [LINBIT/linstor-server#75]
You are 2 node ( A and B )
If Connexion it's StandAlone on each node, and Localy each it's Uptodate

The linstor status, it's "uptodate" but it's wong because it's split brain status.
Need to include global corrum & connexion in status of linstor

Corum need OK
Connexion need Connected
Status need Uptodate

**Comment by raltnoeder** [comment]
LINSTOR basically just reports what DRBD tells it by means of an event stream. A resource can also be legitimately UpToDate when it's not connected, or even when all other peers are down (that's one of the main reasons why DRBD exists). LINSTOR does not detect split brain (and the DRBD events stream also does not report it).
Reporting quorum could possibly be implemented, since quorum changes are reported on the events stream. Also, if Quorum is enabled, then the split brain should theoretically not have occurred in the first place. Proper fencing would be an even safer method, but the limitations of cloud and containerized environments often make it virtually impossible to implement.

All of that being said, LINSTOR reports resource status mostly as a convenience feature for a quick overview of what's going on, but it is not designed for in-depth monitoring and diagnostics. That is the job of other utilities, like drbdmon (included in drbd-utils) and drbdtop, which are designed to help with diagnosing resource, connection, volume and quorum status.

**Comment by proceau** [comment]
The state of connexion it's easy for linstor-satellite to report on linstor-controller with egale methode of update, it's important information.

I'm see this case:
  A - diskless of res InUse ( use by VM )
  B - localdisk of res notused
  C - localdisk of res notused

when you call: disk-toggle ressource -from B A res
it's add localdisk on A
sync A
delete B

but some time, A get Update state without resync, and C get Outdate state
and node A et C set StandAlone by security, and B it's deleted

consequence the DevBlock it's Dead ( A not have any data ), and big probabilité
A resync to C and drop the data :-( ( the fast recovery with standard tools erase data )

On 100 test of disk-toggle 3 it's in this case :-(

Only solution, need down VM, force Primary on C, Secondary on A, Outdate on A, and reconnect A on C with drop localdata, it's not easy and very dangerous

**Comment by proceau** [comment]
un other case, on PVE, with outdate status, and force reconnection, the result it's Kernel Panic and reboot of Host

**Comment by raltnoeder** [comment]
That does indeed sound like a bug in DRBD 9.0.x. If you can reproduce the problem, we would be interested in information about the environment, such as the exact version of the kernel, the DRBD module, the drbd-utils and how the resource that caused the problem was configured.
Log output and a copy of the resource configuration file would help even more.
This would best be posted to the drbd-users mailing group, or as an issue to the DRBD repository here on github.
