### ISSUE TITLE
Feature request: --do-not-place-on AUX_NODE_PROPERTY

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#79]
Hi, it would be nice to have an ability to avoid placing resources on nodes with specific aux property along with `--replicas-on-same` and `--replicas-on-different` options.

Thanks!

**Comment by ghernadi** [comment]
And what exactly is not working as you expect?

Here is how I tested:
I have 2 nodes, `bravo` and `charlie`.  
`bravo` has already a dummy resource deployed so it has less free space than `charlie`. That menas, that `charlie` would be preferred for the next auto-place
```
LINSTOR ==> sp l
╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool ┊ Node    ┊ Driver ┊ PoolName ┊ FreeCapacity ┊ TotalCapacity ┊ SupportsSnapshots ┊ State ┊
╞══════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ lvmpool     ┊ bravo   ┊ LVM    ┊ scratch  ┊     8.99 GiB ┊     10.00 GiB ┊ False             ┊ Ok    ┊
┊ lvmpool     ┊ charlie ┊ LVM    ┊ scratch  ┊    10.00 GiB ┊     10.00 GiB ┊ False             ┊ Ok    ┊
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
However, I set an aux-property on `bravo`:
```
LINSTOR ==> n sp bravo --aux test test
SUCCESS:
...
LINSTOR ==> n lp bravo
╭───────────────────────────╮
┊ Key             ┊ Value   ┊
╞═══════════════════════════╡
┊ Aux/test        ┊ test    ┊
┊ CurStltConnName ┊ default ┊
┊ NodeUname       ┊ bravo   ┊
╰───────────────────────────╯
```
And then `auto-place` the new resource:
```
LINSTOR ==> r c --auto-place 1 rsc --replicas-on-same test=test
SUCCESS:
Description:
    Resource 'rsc' successfully autoplaced on 1 nodes
Details:
    Used storage pool: 'lvmpool'
    Used nodes: 'bravo'
SUCCESS:
    Created resource 'rsc' on 'bravo'
SUCCESS:
Description:
    Resource 'rsc' on 'bravo' ready
Details:
    Auto-placing resource: rsc

LINSTOR ==> r l
╭─────────────────────────────────────────────────╮
┊ ResourceName ┊ Node  ┊ Port ┊ Usage  ┊    State ┊
╞═════════════════════════════════════════════════╡
┊ dummy        ┊ bravo ┊ 7000 ┊ Unused ┊ UpToDate ┊
┊ rsc          ┊ bravo ┊ 7001 ┊ Unused ┊ UpToDate ┊
╰─────────────────────────────────────────────────╯

LINSTOR ==> sp l
╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool ┊ Node    ┊ Driver ┊ PoolName ┊ FreeCapacity ┊ TotalCapacity ┊ SupportsSnapshots ┊ State ┊
╞══════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ lvmpool     ┊ bravo   ┊ LVM    ┊ scratch  ┊     7.99 GiB ┊     10.00 GiB ┊ False             ┊ Ok    ┊
┊ lvmpool     ┊ charlie ┊ LVM    ┊ scratch  ┊    10.00 GiB ┊     10.00 GiB ┊ False             ┊ Ok    ┊
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by ghernadi** [comment]
My suggestion for this feature would be to extend the current `--replicas-on-different` option to not only accept keys, but (as `--replicas-on-same` already does) accept `key=value` pairs (as one string / one argument). 

If I understood your use case, that should allow you to let linstor select nodes which have all different values for the given key, as well as excluding nodes with a special value of the given key.

Example:

5 Nodes, `node1`, `node2`, `node3`, `node4`, `node5` whereas `node3` has the least free space (i.e. default auto-placer would prefer to avoid `node3` if possible).  
`node1` has the aux key: `key=val1`,  
`node2` has the aux key: `key=val2`,
`node3` has the aux key: `key=val3`,
`node4` has the aux key: `key=val1` (same as `node1`).
`node5` has the aux key: `key=val2` (same as `node2`)

`linstor r c --auto-place 2 rsc1 --replicas-on-different key=val1` would select (`node2` and `node3`) or (`node3` and `node5`).   
`node1` would be discarded because it has `key=val1`. Same goes for `node4`.   
`node2` and `node5` cannot be selected together as both share `val2` as value for the key `key`. 

Whether `node2` is more suited than `node5` may depend on other factors.

I agree that this suggestion might not cover 100% of the same use-cases you suggestion covers, but I would prefer to avoid adding more and more options for the `resource create --auto-place` command if possible.

**Comment by kvaps** [comment]
@ghernadi I think your suggestion is fully compatible with my use case: I just want to avoid placing resource on nodes with specific key.
So `--replicas-on-different key=val1` should never put replica on nodes with `key=val1` set.

**Comment by kvaps** [comment]
> (as --replicas-on-same already does) accept key=value pairs (as one string / one argument).

I didn't know about this feature, good to know, because before I was forced to use, keys like:
```
node1 key-val1=true
node2 key-val2=true
node3 key-val3=true
node4 key-val1=true
node5 key-val2=true
```
and `--replicas-on-same key-val1` to get same behavior

**Comment by ghernadi** [comment]
Just to clarify, the example you have given here, an `--replicas-on-same key-val1` would only choose `node1` and `node4`, nothing else as long as the other nodes do not have `key-val1=true` set.

**Comment by kvaps** [comment]
That's true, our case is to having multiple clusters and separate nodes between them:

Eg we need force linstor to creating resources on specific cluster for workload. That's why we using `cluster-1=true`, `cluster-2=true`, `cluster-3=true` and `--replicas-on-same cluster-1` aux-properties when creating resources.

Now we will switch to the `cluster=1`, `cluster=2`, `cluster=3` aux-properties and `--replicas-on-same cluster=1` key as you said.

It would really nice to have an ability to avoid using specific cluster, eg.  `--replicas-on-different cluster=3` should be enough for us.

Thank you!

**Comment by kvaps** [comment]
Hi @ghernadi, I saw that you were implemented this feature in the latest release, I have one use case when it is not working correctly:

```json
{
  "select_filter": {
    "place_count": 2,
    "storage_pool": "thindata",
    "replicas_on_same": [
      "Aux/opennebula-1"
    ],
    "replicas_on_different": [
      "Aux/moonshot=10",
      "Aux/moonshot=15"
    ]
  },
  "diskless_on_remaining": null
}
```

I would expect that resource will be created avoiding both: `moonshot=10` and `moonshot=15` nodes.
The real behavior is somehow wrong, because it is placing resources on both of them.

**Comment by rp-** [comment]
closing this, as the auto-placer was basically rewritten.
if this issue is still a problem, please open a new issue
